apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-train-deployment-cnn
  labels:
    app: sentiment-train-app-cnn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-train-app-cnn
  template:
    metadata:
      labels:
        app: sentiment-train-app-cnn
    spec:
        containers:
        - name: myapp-container-cnn
          image: mahamarif/sentiment-analysis-s140-cnn
          command: ['bash', '-c', 'python train_cnn.py && tail -f /dev/null']
          volumeMounts:
          - name: sentiment-volume
            mountPath: /model
        volumes:
        - name: sentiment-volume
          persistentVolumeClaim:
            claimName: sentiment-pvc
