apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-train-deployment-nb
  labels:
    app: sentiment-train-app-nb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-train-app-nb
  template:
    metadata:
      labels:
        app: sentiment-train-app-nb
    spec:
        containers:
        - name: myapp-container-nb
          image: mahamarif/sentiment-analysis-s140-nb
          command: ['bash', '-c', 'python naive_bayes.py && tail -f /dev/null']
          volumeMounts:
          - name: sentiment-volume
            mountPath: /model
        volumes:
        - name: sentiment-volume
          persistentVolumeClaim:
            claimName: sentiment-pvc
